import = [
	#"~/.config/alacritty/themes/themes/wombat.toml"
	"~/.config/alacritty/themes/themes/ayu_dark.toml"
]

[font]
size = 7

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
#family = "Hack"

[window]
opacity = 0.8
blur = true

[window.padding]
x = 5
y = 5
